"use client";
/* eslint-disable @next/next/no-html-link-for-pages */

import { SearchForm } from "@/components/search-form";
import { ArrowRightIcon, MapPinIcon, SearchIcon, SparkleIcon } from "@/components/icons";

const portals = [{ name: "Viva Real", className: "portal-viva" }, { name: "OLX", className: "portal-olx" }, { name: "imovelweb", className: "portal-imovel" }];

export function HomePage() {
  return <main className="home-page">
    <header className="site-header container"><a className="brand" href="/"><span className="brand-mark"><span /></span><span>maré<span className="brand-dot">.</span></span></a><nav className="desktop-nav"><a href="#como-funciona">Como funciona</a><a href="#fontes">Nossas fontes</a><a href="#sobre">Sobre a Maré</a></nav><div className="header-actions"><button className="header-link">Entrar</button><button className="button button--outline button--small">Anunciar imóvel</button></div></header>
    <section className="hero container"><div className="hero__copy"><div className="hero-kicker"><span className="hero-kicker__line" /> <span>Garopaba, SC</span></div><h1>Seu lugar em<br /><em>Garopaba</em> começa<br />aqui<span className="hero-period">.</span></h1><p>Uma busca simples para explorar imóveis à venda em Garopaba e conferir os portais que importam.</p></div><div className="hero__search"><SearchForm /><div className="hero-search-note"><SparkleIcon size={15} /> Explore cards demonstrativos e abra uma busca externa em <strong>Viva Real</strong>, <strong>OLX</strong> e <strong>imovelweb</strong></div></div></section>
    <section className="hero-bottom container"><div className="hero-stats"><div><strong>3</strong><span>portais<br />em uma busca</span></div><div><strong>8</strong><span>bairros e praias<br />mapeados</span></div><div><strong>100%</strong><span>foco em<br />Garopaba</span></div></div><div className="hero-scroll"><span className="hero-scroll__line" /><span>role para explorar</span></div></section>
    <section className="trusted" id="fontes"><div className="container trusted-inner"><span className="trusted-label">Você encontra em um só lugar</span><div className="portal-logos">{portals.map((portal) => <span className={portal.className} key={portal.name}>{portal.name}</span>)}</div></div></section>
    <section className="how-section container" id="como-funciona"><div className="section-intro"><span className="eyebrow">Sem complicação</span><h2>Uma busca.<br /><em>Mais possibilidades.</em></h2><p>A Maré reúne os anúncios que você procura e organiza tudo para você decidir com calma.</p><a className="text-link" href="/resultados">Explorar imóveis <ArrowRightIcon size={16} /></a></div><div className="steps"><div className="step-card step-card--active"><span className="step-number">01</span><span className="step-icon"><SearchIcon size={23} /></span><h3>Busque do seu jeito</h3><p>Digite um bairro, uma praia ou o tipo de imóvel que você imagina.</p></div><div className="step-card"><span className="step-number">02</span><span className="step-icon"><MapPinIcon size={23} /></span><h3>Compare as opções</h3><p>Veja preços e detalhes de diferentes portais lado a lado.</p></div><div className="step-card"><span className="step-number">03</span><span className="step-icon"><ArrowRightIcon size={23} /></span><h3>Encontre seu lugar</h3><p>Quando algo chamar atenção, vá direto para o anúncio original.</p></div></div></section>
    <section className="neighborhood-section" id="sobre"><div className="container neighborhood-inner"><div><span className="eyebrow">Garopaba por inteiro</span><h2>Do Centro à<br /><em>beira do mar.</em></h2><p>Descubra as diferentes faces da cidade — e encontre o cenário que combina com a sua próxima história.</p></div><div className="neighborhood-chips"><a href="/resultados?query=Praia+da+Ferrugem"><span className="chip-dot chip-dot--blue" />Ferrugem</a><a href="/resultados?query=Praia+da+Silveira"><span className="chip-dot chip-dot--coral" />Silveira</a><a href="/resultados?query=Centro"><span className="chip-dot chip-dot--green" />Centro</a><a href="/resultados?query=Praia+do+Siriú"><span className="chip-dot chip-dot--gold" />Siriú</a><a href="/resultados?query=Campo+Duna"><span className="chip-dot chip-dot--purple" />Campo Duna</a><a href="/resultados?query=Morrinhos"><span className="chip-dot chip-dot--pink" />Morrinhos</a></div></div></section>
    <footer className="site-footer site-footer--home"><div className="container footer-inner"><div><a className="brand brand--footer" href="/"><span className="brand-mark"><span /></span><span>maré<span className="brand-dot">.</span></span></a><p>Encontrar seu lugar<br />começa por aqui.</p></div><div className="footer-links"><div><strong>Explorar</strong><a href="/resultados?type=house">Casas</a><a href="/resultados?type=apartment">Apartamentos</a><a href="/resultados?type=land">Terrenos</a></div><div><strong>Sobre</strong><a href="#como-funciona">Como funciona</a><a href="#fontes">Nossas fontes</a><a href="#sobre">Contato</a></div><div><strong>Para negócios</strong><a href="#">Anunciar imóvel</a><a href="#">Seja parceiro</a></div></div></div><div className="container footer-bottom"><span>© 2026 Maré Imóveis · Garopaba, SC</span><span>Uma pesquisa, todos os lugares.</span></div></footer>
  </main>;
}
