import crypto from "crypto";
import { describe, expect, it } from "vitest";
import { auditProject } from "@/lib/local-project-analyzer";
import { createInMemorySource } from "@/lib/project-source";
import { isSignatureValid } from "@/app/api/webhooks/github/route";
import { isSafeRef, isSafeSegment } from "@/app/api/sentinel/audit-repo/route";

describe("source-agnostic auditing", () => {
  it("audits files that never touch the local disk", async () => {
    const source = createInMemorySource(
      {
        "package.json": JSON.stringify({ name: "remote-project" }),
        "package-lock.json": "{}",
        Dockerfile: "FROM node:20\nRUN npm install\n",
      },
      "github.com/example/remote-project",
    );

    const report = await auditProject(source);
    const ids = report.findings.map((finding) => finding.id);

    expect(report.projectName).toBe("remote-project");
    expect(report.origin).toBe("github.com/example/remote-project");
    expect(ids).toContain("docker-single-stage");
    expect(ids).toContain("docker-npm-install");
  });

  it("does not demand package-lock.json from a pnpm project", async () => {
    const source = createInMemorySource({
      "package.json": JSON.stringify({ name: "pnpm-project", engines: { node: ">=20" } }),
      "pnpm-lock.yaml": "lockfileVersion: '9.0'\n",
    });

    const report = await auditProject(source);
    expect(report.findings.map((finding) => finding.id)).not.toContain("deps-no-lockfile");
  });

  it("flags a project with no lockfile at all", async () => {
    const source = createInMemorySource({
      "package.json": JSON.stringify({ name: "no-lock", engines: { node: ">=20" } }),
    });

    const report = await auditProject(source);
    expect(report.findings.map((finding) => finding.id)).toContain("deps-no-lockfile");
  });

  it("says it could not analyze rather than inventing findings", async () => {
    const report = await auditProject(createInMemorySource({}, "empty-source"));

    expect(report.analyzable).toBe(false);
    expect(report.findings).toHaveLength(0);
    expect(report.notes.join(" ")).toContain("empty-source");
  });
});

describe("reporting what could not be measured", () => {
  it("parses a tsconfig with a trailing comma before a comment", async () => {
    const source = createInMemorySource({
      "package.json": JSON.stringify({ name: "fixture", engines: { node: ">=20" } }),
      "package-lock.json": "{}",
      "tsconfig.json": '{\n "compilerOptions": {\n  "strict": true, // liga\n }\n}',
    });

    const report = await auditProject(source);

    expect(report.filesUnreadable).not.toContain("tsconfig.json");
    expect(report.findings.map((finding) => finding.id)).not.toContain("ts-strict-off");
  });

  it("does not call an unparseable tsconfig a disabled strict mode", async () => {
    const source = createInMemorySource({
      "package.json": JSON.stringify({ name: "fixture", engines: { node: ">=20" } }),
      "package-lock.json": "{}",
      "tsconfig.json": '{ "compilerOptions": { "strict": true }',
    });

    const report = await auditProject(source);

    expect(report.findings.map((finding) => finding.id)).not.toContain("ts-strict-off");
    expect(report.filesUnreadable).toContain("tsconfig.json");
    expect(report.notes.join(" ")).toContain("could not be parsed");
  });

  it("does not audit a runtime directory that only holds a package.json", async () => {
    // What a Next standalone image looks like at /app.
    const source = createInMemorySource(
      {
        "package.json": JSON.stringify({ name: "sentinelops-ai", version: "0.1.0" }),
        "server.js": "// generated by next build --standalone",
      },
      "/app",
    );

    const report = await auditProject(source);

    expect(report.analyzable).toBe(false);
    expect(report.findings).toHaveLength(0);
    expect(report.notes.join(" ")).toContain("deployed runtime");
  });

  it("still audits a project that has a lockfile but nothing else", async () => {
    const source = createInMemorySource({
      "package.json": JSON.stringify({ name: "minimal" }),
      "package-lock.json": "{}",
    });

    const report = await auditProject(source);

    expect(report.analyzable).toBe(true);
    expect(report.findings.map((finding) => finding.id)).toContain("deps-no-engines");
  });

  it("refuses to analyze when package.json cannot be parsed", async () => {
    const source = createInMemorySource({ "package.json": "{ not json" });

    const report = await auditProject(source);

    expect(report.analyzable).toBe(false);
    expect(report.findings).toHaveLength(0);
    expect(report.filesUnreadable).toContain("package.json");
  });
});

describe("repository path validation", () => {
  it("accepts ordinary owner and repo names", () => {
    expect(isSafeSegment("vercel")).toBe(true);
    expect(isSafeSegment("next.js")).toBe(true);
  });

  it("rejects dot segments that would traverse the API path", () => {
    expect(isSafeSegment(".")).toBe(false);
    expect(isSafeSegment("..")).toBe(false);
    expect(isSafeSegment("a/b")).toBe(false);
  });

  it("rejects refs containing dot segments", () => {
    expect(isSafeRef("main")).toBe(true);
    expect(isSafeRef("release/1.0")).toBe(true);
    expect(isSafeRef("../secret")).toBe(false);
  });
});

describe("github webhook signature", () => {
  const secret = "s3cr3t";
  const body = JSON.stringify({ action: "opened" });
  const valid = `sha256=${crypto.createHmac("sha256", secret).update(body).digest("hex")}`;

  it("accepts a signature computed with the shared secret", () => {
    expect(isSignatureValid(body, valid, secret)).toBe(true);
  });

  it("rejects a missing signature", () => {
    expect(isSignatureValid(body, null, secret)).toBe(false);
  });

  it("rejects a signature made with a different secret", () => {
    const forged = `sha256=${crypto.createHmac("sha256", "wrong").update(body).digest("hex")}`;
    expect(isSignatureValid(body, forged, secret)).toBe(false);
  });

  it("rejects a signature of a different body", () => {
    expect(isSignatureValid(JSON.stringify({ action: "closed" }), valid, secret)).toBe(false);
  });

  it("rejects a malformed signature without throwing", () => {
    expect(isSignatureValid(body, "sha256=short", secret)).toBe(false);
  });
});

describe("expanded checks", () => {
  const base = {
    "package.json": JSON.stringify({ name: "fixture", engines: { node: ">=20" } }),
    "package-lock.json": "{}",
    ".gitignore": "node_modules\n.env*\n",
  };

  it("flags a base image with no tag and one on latest", async () => {
    const report = await auditProject(
      createInMemorySource({
        ...base,
        Dockerfile: "FROM node AS builder\nFROM node:latest AS runner\nUSER app\n",
      }),
    );

    const finding = report.findings.find((item) => item.id === "docker-unpinned-base");
    expect(finding).toBeDefined();
    expect(finding!.evidence).toContain("FROM node:latest");
  });

  it("accepts a pinned base image", async () => {
    const report = await auditProject(
      createInMemorySource({
        ...base,
        Dockerfile: "FROM node:20-alpine AS builder\nFROM node:20-alpine AS runner\nUSER app\n",
      }),
    );

    expect(report.findings.map((item) => item.id)).not.toContain("docker-unpinned-base");
  });

  it("flags COPY . . only when there is no .dockerignore", async () => {
    const dockerfile =
      "FROM node:20-alpine AS builder\nCOPY . .\nFROM node:20-alpine AS runner\nUSER app\n";

    const without = await auditProject(createInMemorySource({ ...base, Dockerfile: dockerfile }));
    const withIgnore = await auditProject(
      createInMemorySource({ ...base, Dockerfile: dockerfile, ".dockerignore": "node_modules\n" }),
    );

    expect(without.findings.map((i) => i.id)).toContain("docker-copy-all");
    expect(withIgnore.findings.map((i) => i.id)).not.toContain("docker-copy-all");
  });

  it("flags a file fetched over the network at build time", async () => {
    const report = await auditProject(
      createInMemorySource({
        ...base,
        Dockerfile:
          "FROM node:20-alpine AS a\nADD https://example.com/tool.tar.gz /tmp/\nFROM node:20-alpine AS b\nUSER app\n",
      }),
    );

    expect(report.findings.map((i) => i.id)).toContain("docker-remote-add");
  });

  it("flags a dependency installed from git", async () => {
    const report = await auditProject(
      createInMemorySource({
        ...base,
        "package.json": JSON.stringify({
          name: "fixture",
          engines: { node: ">=20" },
          dependencies: { good: "^1.0.0", risky: "git+https://example.com/pkg.git" },
        }),
      }),
    );

    const finding = report.findings.find((i) => i.id === "deps-remote-source");
    expect(finding).toBeDefined();
    expect(finding!.evidence).toContain("risky");
    expect(finding!.evidence).not.toContain("good");
  });

  it("accepts the /node_modules form that every Next template writes", async () => {
    const report = await auditProject(
      createInMemorySource({ ...base, ".gitignore": "/node_modules\n.env*\n" }),
    );

    expect(report.findings.map((i) => i.id)).not.toContain("gitignore-node-modules");
  });

  it("flags a .gitignore that does not cover node_modules", async () => {
    const report = await auditProject(
      createInMemorySource({ ...base, ".gitignore": ".env*\n" }),
    );

    expect(report.findings.map((i) => i.id)).toContain("gitignore-node-modules");
  });
});
